### ISSUE TITLE
The build for macOS doesn't seem to be working

### ISSUE THREAD

**Issue by dihelium** [DankMemer/Dank-Memer-CLI#3]
Hi, I ran ./copypasta-mac and ./"copypasta-mac" as well from my downloads folder, and it gives me the error:
```
./copypasta-mac: command not found
```

**Comment by melmsie** [comment]
I'll look into this in a few hours, thanks for the heads up

**Comment by dihelium** [comment]
Hi, it seems that the issue stemmed from macOS converting the executable into a text file. For anyone else that faces this problem, do a chmod +x for the file, and it'll get converted into an executable. It runs perfectly after that.
